#!/usr/bin/env bash
# Regenerate setup-go-public-skill.sh from the live source tree.
# Run from repo root: scripts/build-installer.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="$ROOT/setup-go-public-skill.sh"

# Operational files only — no fixtures/ or tests/ (dev harness).
MANIFEST=(
  ".cursor/skills/go-public/SKILL.md"
  "scripts/go-public"
  "scripts/go-public-lib/common.sh"
  "scripts/go-public-lib/git.sh"
  "scripts/go-public-lib/report.sh"
  "scripts/go-public-lib/audit.sh"
  "scripts/go-public-lib/docs.sh"
  "scripts/go-public-lib/history.sh"
  "scripts/go-public-lib/verify_clone.sh"
  "adapters/generic.sh"
  "adapters/go.sh"
  "adapters/node.sh"
  "adapters/python.sh"
  "adapters/rust.sh"
  ".go-public.yaml"
  ".gitleaks.toml"
  "LICENSE"
  "README.md"
)

encode_file() {
  local path="$1"
  if base64 --help 2>&1 | grep -q GNU; then
    base64 -w 0 "$path"
  else
    base64 <"$path" | tr -d '\n'
  fi
}

{
  cat <<'INSTALLER_HEAD'
#!/usr/bin/env bash
# Self-contained go-public skill installer.
# Generated by scripts/build-installer.sh — regenerate instead of editing by hand.
#
# Usage (from repo root):
#   bash setup-go-public-skill.sh
#   git add -A && git commit -m "Add go-public skill"
#
# Writes the skill + CLI toolchain only. No git, remote, or network operations.
set -euo pipefail

TARGET_ROOT="${1:-.}"
TARGET_ROOT="$(cd "$TARGET_ROOT" && pwd)"

b64_decode() {
  if echo "dGVzdA==" | base64 -d >/dev/null 2>&1; then
    base64 -d
  else
    base64 -D
  fi
}

write_b64() {
  local rel="$1"
  local dest="$TARGET_ROOT/$rel"
  mkdir -p "$(dirname "$dest")"
  b64_decode >"$dest"
}

INSTALLER_HEAD

  for rel in "${MANIFEST[@]}"; do
    [[ -f "$ROOT/$rel" ]] || { echo "Missing: $rel" >&2; exit 1; }
    tag="__B64_$(echo "$rel" | tr '/.' '__')"
    {
      echo "write_b64 '$rel' <<'$tag'"
      encode_file "$ROOT/$rel"
      echo
      echo "$tag"
      echo
    }
  done

  cat <<'INSTALLER_TAIL'
chmod +x "$TARGET_ROOT/scripts/go-public"

echo "go-public skill installed under $TARGET_ROOT"
echo "  Skill:  .cursor/skills/go-public/SKILL.md"
echo "  CLI:    scripts/go-public audit --dry-run"
INSTALLER_TAIL
} >"$OUTPUT"

chmod +x "$OUTPUT"
echo "Wrote $OUTPUT (${#MANIFEST[@]} files embedded)"
